inherits_from:
  - .haml-lint_todo.yml

exclude:
  - vendor/**/*

# Whether to ignore frontmatter at the beginning of HAML documents for
# frameworks such as Jekyll/Middleman
skip_frontmatter: false

linters:
  AltText:
    enabled: false

  ClassAttributeWithStaticValue:
    enabled: true

  ClassesBeforeIds:
    enabled: true

  # Seems to default to true anyway, but uncommenting it interferes with the TODO file
  # ConsecutiveComments:
  #   enabled: true

  ConsecutiveSilentScripts:
    enabled: true
    max_consecutive: 2

  EmptyScript:
    enabled: true

  HtmlAttributes:
    enabled: false

  ImplicitDiv:
    enabled: true

  LeadingCommentSpace:
    enabled: true

  LineLength:
    enabled: true
    max: 300

  MultilinePipe:
    enabled: true

  MultilineScript:
    enabled: true

  ObjectReferenceAttributes:
    enabled: true

  RuboCop:
    enabled: false

  RubyComments:
    enabled: true

  SpaceBeforeScript:
    enabled: true

  # Seems to default to true anyway, but uncommenting it interferes with the TODO file
  # SpaceInsideHashAttributes:
  #   enabled: true
  #   style: space

  TagName:
    enabled: true

  TrailingWhitespace:
    enabled: true

  # Seems to default to true anyway, but uncommenting it interferes with the TODO file
  # UnnecessaryInterpolation:
  #   enabled: true

  UnnecessaryStringOutput:
    enabled: true
